#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world
#EXCLUDE_COMPONENTS :=$(IDF_PATH)/components/esp32 $(IDF_PATH)/components/app_trace 

include $(IDF_PATH)/make/project.mk

